#!/bin/sh

NAME=phb_test
RELEASE=12
YEAR=25
VERSION=0006

EXCLUDE="-m .git -m .gitignore -m LICENSE"
EXCLUDE="$EXCLUDE -m System -m boot/grub/i386-pc -m boot/grub/x86_64-efi -m boot.catalog -m efi.img -m mach_kernel"

[ -f boot/grub/grub.cfg ] || exit

for FILE in 01-filesystem.squashfs initrd1.xz vmlinuz1
do test -f live/${FILE} || exit
done

#sudo apt-get install -y grub-common grub-pc-bin grub-efi-amd64-bin mtools xorriso

find live* -type f | sort | xargs md5sum > md5sum.txt

rm -f ${NAME}_x64_${RELEASE}_${YEAR}_${VERSION}_vtgrub2.iso
rm -f ${NAME}_${RELEASE}_${YEAR}_${VERSION}_vtgrub2.iso
grub-mkrescue --locales= -volid ${NAME} -m '*.iso' ${EXCLUDE} -m live32 -o ${NAME}_x64_${RELEASE}_${YEAR}_${VERSION}_vtgrub2.iso ./
[ -d live32 ] && grub-mkrescue --locales= -volid ${NAME} -m '*.iso' ${EXCLUDE} -o ${NAME}_${RELEASE}_${YEAR}_${VERSION}_vtgrub2.iso ./
