#!/bin/sh

NAME=phb_test
RELEASE=12
YEAR=25
VERSION=0002

EXCLUDE="-m .gitignore -m LICENSE -m System* -m boot/grub/i386-pc* -m boot/grub/x86_64-efi* -m boot.catalog -m efi.img -m mach_kernel"

[ -f boot/grub/grub.cfg ] || exit

for FILE in 01-filesystem.squashfs initrd1.xz vmlinuz1
do test -f live/${FILE} || exit
done

#sudo apt-get install -y grub-common grub-pc-bin grub-efi-amd64-bin mtools xorriso

rm -f ${NAME}_x64_${RELEASE}_${YEAR}_${VERSION}_vtgrub2.iso
grub-mkrescue --locales= -volid ${NAME} ${EXCLUDE} -m live32* -o ${NAME}_x64_${RELEASE}_${YEAR}_${VERSION}_vtgrub2.iso ./
